const BAD_REQUEST = "BAD_REQUEST";
const SERVER_ERROR = "SERVER_ERROR";
const NOT_FOUND = "NOT_FOUND";
const UNAUTHORIZED = "UNAUTHORIZED";

export {
	BAD_REQUEST,
	SERVER_ERROR,
	NOT_FOUND,
	UNAUTHORIZED,
};
